#!  /bin/bash
#RM_SELINUX_RULE=enable
#
#  PRNL=
#  PRNC=
#  PRNP=hll9470cdnpdrv-3.5.0-1a.i386.deb
#  SCAN=
#  SKEY=
#
if ! [ -f /etc/init.d/cupsys ];then
 DUMMYCUPSYS=1
 ln -s /bin/true  /etc/init.d/cupsys
fi
if ! [ -f /etc/init.d/cups ];then
 DUMMYCUPS=1
 ln -s /bin/true  /etc/init.d/cups
fi
if ! [ -f /etc/init.d/lpd ];then
 DUMMYLPD=1
 ln -s /bin/true  /etc/init.d/lpd
fi
if ! [ -f /etc/init.d/lprng ];then
 DUMMYLPRNG=1
 ln -s /bin/true  /etc/init.d/lprng
fi
dpkg  -x hll9470cdnpdrv-3.5.0-1.i386.deb /
dpkg  -P    hll9470cdnpdrv
