#!  /bin/bash
#RM_SELINUX_RULE=enable
#
#  PRNL=mfcl8900cdwlpr-1.5.0-0a.i386.deb
#  PRNC=mfcl8900cdwcupswrapper-1.5.0-0a.i386.deb
#  PRNP=
#  SCAN=brscan4-0.4.11-1.i386.deb
#  SKEY=brscan-skey-0.3.2-0.i386.deb
#
if ! [ -f /etc/init.d/cupsys ];then
 DUMMYCUPSYS=1
 ln -s /bin/true  /etc/init.d/cupsys
fi
if ! [ -f /etc/init.d/cups ];then
 DUMMYCUPS=1
 ln -s /bin/true  /etc/init.d/cups
fi
if ! [ -f /etc/init.d/lpd ];then
 DUMMYLPD=1
 ln -s /bin/true  /etc/init.d/lpd
fi
if ! [ -f /etc/init.d/lprng ];then
 DUMMYLPRNG=1
 ln -s /bin/true  /etc/init.d/lprng
fi
dpkg  -x mfcl8900cdwcupswrapper-1.5.0-0.i386.deb /
dpkg  -P    mfcl8900cdwcupswrapper:i386
dpkg  -x mfcl8900cdwlpr-1.5.0-0.i386.deb /
dpkg  -P    mfcl8900cdwlpr:i386
